### ISSUE TITLE
Better Mobile Support

### ISSUE THREAD

**Issue by revantemp3** [n1crack/vuefinder#74]
Hi, thank you for the impressive features and beautiful design

I think the component is excellent for people who used a computer before the mobile era but it needs better mobile support.

**Issue 1: dragging on blank area does not scroll up or down**

The scroll bar is quite small on mobile devices and an end user is probably not used to dragging a scroll bar (thanks to Steve Jobs)

I think dragging on blank area competes with selecting multiple files, so it is not something I want to fork and rewrite atm

perhaps vuefinder can expose an option for devs to choose between drag to select files vs drag to scroll?

**Issue 2: No long press to select multiple files**
Right now long press opens the context menu, which is a great idea.  I think we also need to add an option to Select the file in the context menu

**Issue 3: support for pagination**
This was an issue raised by the community before. I think it is quite important to allow breaking up file infos for mobile connection

My idea goes like this:
if "partial" mode is set to on, when vuefinder loads, it asks backend for the total number of files (n) and the first 10 or 20 files

when a user scrolls down, request the next 10 files etc

n is used to estimate how much further a user can scroll down

Cheers

**Comment by n1crack** [comment]
Dragging is not possible because of the selecting area, instead you can move up or down while selecting. Scrollbar was hidden as default on ios devices, and was never shown when you try so I used a scrollbar component to make it always visible.

Current design allows us both to select area and use scrollbar. Otherwise, I don't think it would provide a better user experience.

It would be very nice if we had select / unselect items in the context menu, but it is quite a work for now. I will look into it later. 

I didn't get any issues when using scrollbars yet but just let you know  it is possible to change width of the scrollbar when using mobile with a few lines of css. 

Pagination or infinite scrollbar or whatever you call it, is something in my mind for a long time. It will be added near future. You can read the roadmap post in the discussion section.

Thanks.

**Comment by revantemp3** [comment]
Thanks for the extensive reply.

I suppose you are right, scrollbar seems to be only an issue for a particular device (the samsung fold 5 i use) which has an exceedingly height vs width ratio.  A lot of UI is messed up on that device too so it is not necessarily a problem on vuefinder.

Exciting about the new features, cheers

**Comment by n1crack** [comment]
@revantemp3 Btw, you are right about when the folder is empty, scrollbar should be shown, Need to add min-height to container div. that was also in my todo list. 

I’m currently switching jobs, thats why Im so busy.. Sorry If I delay the new features a bit.
